### ISSUE TITLE
Does this project have a consistent maintenance?

### ISSUE THREAD

**Issue by hsblhsn** [arsmn/gqlgen#1]
Is it okay to use this project in production applications?

Is this project being maintained regularly?

Will this project follow the next releases of `gqlgen`? Or is it just for this forked version only?

English is not my first language. So If something is not clear, please reply, I will describe it again.

**Comment by arsmn** [comment]
Hi @hsblhsn 
Sorry for late response
Personally, I've not used it in production yet
Yes I try to keep it up to date on each gqlgen release

**Comment by arsmn** [comment]
I close this issue but feel free to open issues if you encounter any bugs
