### ISSUE TITLE
Unable to install fastgql

### ISSUE THREAD

**Issue by lmnzx** [arsmn/gqlgen#3]
### What happened?
I am unable to install arsmn/fastgql
`go get github.com/arsmn/fastgql` give an error:
```go get: github.com/arsmn/fastgql@v0.7.2 updating to
        github.com/arsmn/fastgql@v0.14.0 requires
        github.com/fasthttp/websocket@v1.4.3: reading github.com/fasthttp/websocket/go.mod at revision v1.4.3: unknown revision v1.4.3
```

### versions
 - `go version go1.16.4 linux/amd64`

**Comment by juanjoseluisgarcia** [comment]
`go get -u github.com/arsmn/fastgql` worked for me

**Comment by sujamess** [comment]
> `go get -u github.com/arsmn/fastgql` worked for me

It didn't work out as well. The official version of `fasthttp/websocket` is `1.4.2`, but version `1.4.3` is in the works

I suggest that we should downgrade to version `1.4.2` of `fasthttp/websocket` until they release a new version
