### ISSUE TITLE
graph/prelude.resolvers.go:19:44: __DirectiveResolver not exported by package generated

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [arsmn/gqlgen#4]
### What happened?
When I do fastgql generate I get the error: `graph/prelude.resolvers.go:19:44: __DirectiveResolver not exported by package generated`

### What did you expect?
Files be generated

### versions
 - `gqlgen version`? v0.13.0-dev
 - `go version`? 1.17
 - dep or go modules? modules

**Comment by Hamzsd** [comment]
How did this issue solve for you?
