### ISSUE TITLE
Go Fiber v2

### ISSUE THREAD

**Issue by saul-data** [arsmn/gqlgen#8]
Are there any examples on how to use Go Fiber v2?

**Comment by arsmn** [comment]
graphql recipe: https://github.com/gofiber/recipes/tree/master/graphql

**Comment by saul-data** [comment]
Thank you. How about subscriptions?

**Comment by akbarfa49** [comment]
@saul-data can you try https://github.com/akbarfa49/gqlgen/tree/fasthttp_implementation ?

first, you need to clone and put this into your project directory and then inside gomod :

replace github.com/99designs/gqlgen => ./dir/gqlgen

//code example

`
srv := handler.NewDefaultFastServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{
		ChatMessages:  []*model.Message{},
		ChatObservers: map[string]chan []*model.Message{},
	}}))

	app := fiber.New()

	app.Use(cors.New())
	app.All(`/`, HTTPHandler(playground.Handler("GraphQL playground", "/query")))
	app.All(`/query`, func(c *fiber.Ctx) error {
		srv.ServeHTTP(c.Context())

		return nil
	})
	fmt.Println(app.Listen(`:4000`))
`

**Comment by arsmn** [comment]
Follow chat example: https://github.com/arsmn/fastgql/tree/master/example/chat
